### ISSUE TITLE
UTM data not populated

### ISSUE THREAD

**Issue by fcontell** [tcampb/calendly-for-salesforce-flow#1]
I'm using this component in multiple flows and screens. It works well most of the time but I have one case where all other data is populated correctly except the UTM fields (they remain blank). In the same flow I use the component in another screen and works well. I tried deleting the component and setting it up again and also cloning the other screen and just changing the URL but it is still showing the same result. Any ideas?

I've implemented a workaround but just wondering why that could be. Thank you!

**Comment by tcampb** [comment]
Hey @fcontell, would you be able to share a video / screenshots of your flow setup?

**Comment by fcontell** [comment]
This one works:
![iScreen Shoter - Google Chrome - 240311160115](https://github.com/tcampb/calendly-for-salesforce-flow/assets/103349896/2f624cd8-676a-411f-b837-5bd19c2ecb63)

This doesn't:
![iScreen Shoter - Google Chrome - 240311160151](https://github.com/tcampb/calendly-for-salesforce-flow/assets/103349896/05cf71d3-12d7-4f6a-8d85-efe92cbafa7f)

Let me know if you'd like to see something else.

**Comment by tcampb** [comment]
Thanks @fcontell. From what I see in the screenshots, it seems like the only difference is the UTM content text value which shouldn't make a difference. Are the screens being loaded in different ways? For example, is one screen after the other? I'm wondering if it's an issue with the component not re-rendering.

**Comment by fcontell** [comment]
Not really. Sometime both might be loaded but my tests are usually once each. This is the setup. The red one does not pass the UTM values. The green one does.
![iScreen Shoter - Google Chrome - 240312095927](https://github.com/tcampb/calendly-for-salesforce-flow/assets/103349896/9085939f-2c9e-4656-86e4-aa5d624d6276)

**Comment by tcampb** [comment]
@fcontell - I tried my best to re-create the flow above and wasn't able to recreate the issue. Both screens included the utm parameters when the event was scheduled.

> I've implemented a workaround but just wondering why that could be. Thank you!



Is the workaround in the flow? If so, could you share what you changed to make it work? This might help me understand what be causing the underlying issue.

**Comment by fcontell** [comment]
@tcampb It is a weird behavior. Maybe it is something with Flow rather than the component. It is a rather big Flow, so I cannot re-create it from scratch without denting the client's budget.

The workaround I implemented is using the slug field (that comes populated from Calendly) to identify the event so I could add the information after the record was created, so not really fixing the issue, just not using the UTM fields. In any case, I'm deeply grateful for the component :)
